

services:
  compiler-backend:
    build: ./CompilerBackend
    ports:
      - "5000:5000"
    env_file:
     - ./CompilerBackend/.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

  coderunner:
    build: ./CompilerBackend/CodeRunner
    restart: unless-stopped
